### ISSUE TITLE
could not start ipfix server

### ISSUE THREAD

**Issue by Amfy** [Exa-Networks/exaddos#1]
Hello,

On all our systems I receive a "could not start ipfix server". Doesn't matter where I bind it to, what port I use, etc.

**Comment by thomas-mangin** [comment]
Could it be that you are trying a port < 1024 without being root ? Otherwise without more information we can only guess.

**Comment by yeled** [comment]
I get it too, here is the dump

```
8:12 netmon1:~/src/exaddos% sudo ./sbin/exaddos -c exaddos.conf.snmpv2
http server on 10.7.3.135:8181
starting snmp clients
starting snmp clients
starting snmp clients
starting ipfix consummer
starting ipfix consummer
starting ipfix consummer
starting ipfix server
starting http server


--------------------------------------------------------------------------------
-- Please provide the information below: https://github.com/Exa-Networks/exaddos
--------------------------------------------------------------------------------
could not start ipfix server


-- Version

2.6.7 (r267:88850, Dec  2 2011, 20:27:26)
[GCC 4.4.3]


-- Traceback


Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/nail/home/charlie/src/exaddos/lib/exaddos/debug.py", line 59, in <module>
    execfile(sys.argv[0])
  File "/nail/home/charlie/src/exaddos/lib/exaddos/application.py", line 311, in <module>
    reactor.run()
  File "/nail/home/charlie/src/exaddos/lib/exaddos/reactor.py", line 70, in run
    raise exc_obj
ImportError: cannot import name NoSuchInstance


--------------------------------------------------------------------------------
-- Please provide the information above: https://github.com/Exa-Networks/exaddos
--------------------------------------------------------------------------------


8:13 netmon1:~/src/exaddos%
```

```
8:13 netmon1:~/src/exaddos% cat exaddos.conf.snmpv2
[exaddos.daemon]
user = 'nobody'

[exaddos.http]
host = '10.7.3.135'
port = 8181

[exaddos.ipfix]
host = 'xxx.xxx.xxx.xxx'
port = 9000


[exaddos.location]
database = 'data/exaddos/db/exaddos.sqlite3'
html = 'data/exaddos/html'

[exaddos.profile]
destination = 'stdout'
enable = false

# threshold: expressed in pps

[exaddos.PEER1]
router = '127.0.0.2'
snmp_version = 2
snmp_password = 'secret'
snmp_frequency = 10
snmp_index_port = 120
snmp_index_vlan = 100
threshold_bandwidth = 104857600
threshold_unicast = 120000
threshold_notunicast = 1500


[exaddos.PEER2]
router = '127.0.0.2'
snmp_version = 2
snmp_password = 'secret'
snmp_frequency = 10
snmp_index_port = 120
snmp_index_vlan = 110
threshold_bandwidth = 104857600
threshold_unicast = 120000
threshold_notunicast = 1500


[exaddos.TRANSIT1]
router = '127.0.0.3'
location = 'datacenter'
snmp_version = 2
snmp_password = 'secret'
snmp_frequency = 10
snmp_index_port = 220
snmp_index_vlan = 140
threshold_bandwidth = 104857600
threshold_unicast = 120000
threshold_notunicast = 1500
8:13 netmon1:~/src/exaddos%
```

Ubuntu Lucid :(

**Comment by thomas-mangin** [comment]
The program is failing when trying to use the pysnmp library :
from pysnmp.proto.rfc1905 import NoSuchInstance

I am testing for the presence of the library. If it is not present you should get :

```
This program requires python netsnmp
> pip install pysnmp
> pip install pysnmp_mibs
```

So it seems that the version present does not have this API. Could you please tell me where pysnmp came from. If it is a debian packet and if you can, please un-install it and see if using pip fixes the problem.

**Comment by thomas-mangin** [comment]
Please consider using https://github.com/pavel-odintsov/fastnetmon I have no time for exaddos development and fastnetmon is much better.
